### ISSUE TITLE
distinguish between exit and die

### ISSUE THREAD

**Issue by nuno-silva** [viraptor/phply#28]
The `Exit` node is used for both `die()` and `exit()` constructs. Even though they are equivalent, it would be useful to either:
- Use a different node for `die()` and `exit()`
- Add an attribute (e.g. name) to the `Exit` node

**Comment by viraptor** [comment]
Good idea. I'll make them separate nodes.

**Comment by soulseekah** [comment]
Well, see, both exit and die are the same node in PHP.

See: https://github.com/php/php-src/blob/2cc3aeb4b98bcbc9572041b2f7d3276aabd51aae/Zend/zend_language_scanner.l#L1125-L1131

It's a `T_EXIT` token with no distinctions.

Although, I think that die has to be called as a function, while exit can be just called as is:

`die();` vs. `exit;`

@nuno-silva what's your issue with looking at exit (w/ or without parameters)? I can see you're looking at it as a sink, both exit and die would behave the same way (with or without parameters), right?

**Comment by nuno-silva** [comment]
@soulseekah they would behave the same, yes. However, in the tool I was working on, it would be "weird" for a `die` in the configuration file to also match an `exit` call, though they are semantically the same.

@viraptor to be consistent with Zend, I don't think there's a need to make them separate nodes. As far as I'm concerned, a `name` attribute would do. Don't worry too much, though, as I won't be working on my "SS1617" project so soon ;)

**Comment by viraptor** [comment]
I see the point of at least annotating which one was used. One would be for any project which wants to do a roundtrip to a similar PHP representation. Another one is just for better user reports ("Foobar kind of problem when you call "die" on line 123").

But I agree another node is not really necessary. Maybe just an attribute to identify them?

**Comment by viraptor** [comment]
@nuno-silva Let me know if the PR referenced above works for you.

**Comment by nuno-silva** [comment]
@viraptor thank you for the change. See my comment in the PR.
