### ISSUE TITLE
PHP predefined constants are not available.

### ISSUE THREAD

**Issue by hartym** [viraptor/phply#4]
A list of those constants are available at the following URL.

http://php.net/manual/en/reserved.constants.php

I noticed it because I tryed to run 

``` php
<?php
echo 'test'.PHP_EOL;
```

**Comment by soulseekah** [comment]
That will be parsed as a Constant without throwing any errors. Doesn't have to be interpreted and resolved to an exact meaning.

**Comment by viraptor** [comment]
Thanks for the report!
The resolution is what @soulseekah said. Parsing handles those already at the moment.
