### ISSUE TITLE
Incomplete installation on Windows

### ISSUE THREAD

**Issue by FriedrichFroebel** [viraptor/phply#40]
When trying to use the package with Python 3.6.3 on Windows 8.1, I cannot import the needed modules:

```
>>> from phply import phpast
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'phpast'
```

The only module I can import is `phply.parsetab`. Using `python -m pip install phply`, the only module which has been installed is `C:\Python\Lib\site-packages\phply\parsetab.py`, whereas there are some more files on Ubuntu (where the above code works fine).

**Comment by viraptor** [comment]
I'll see what I can find out, but I don't have any access to windows machines, so it's a bit hard to debug.

Could you checkout the repo, build it using `python setup.py sdist`, and post the tree of files in the created zip file? That would be very helpful.

**Comment by FriedrichFroebel** [comment]
I cloned the latest master branch and get the following tree:

```
.
|   PKG-INFO
|   README.md
|   setup.cfg
|   setup.py
|   tree.txt
|   
+---phply
|       phpast.py
|       phplex.py
|       phpparse.py
|       pythonast.py
|       __init__.py
|       
+---phply.egg-info
|       dependency_links.txt
|       entry_points.txt
|       namespace_packages.txt
|       not-zip-safe
|       PKG-INFO
|       requires.txt
|       SOURCES.txt
|       top_level.txt
|       
\---tests
        test_filtered_lexer.py
        test_lexer.py
        test_parser.py
        __init__.py
```

Installing `phply` using `python -m setup install` from the cloned repository works, so there seems to be a problem with the direct pip installation.

**Comment by viraptor** [comment]
I can't find anything strange with the package. For the new version I published both the sdist and a wheel distribution. Let me know if that solves the problem.

**Comment by FriedrichFroebel** [comment]
It seems to work now. Forcing the installation of the old 1.2.1 release did work this time, too, so somehow strange seemed to have happened last time.
