### ISSUE TITLE
SyntaxError when parsing php files

### ISSUE THREAD

**Issue by RicterZ** [viraptor/phply#44]
I wrote a script to parse php files, the first file works well, but when parsing the second php file, it raise a SyntaxError. I noticed the first file not enclosed by `?>`, I added `?>` at the file end and then the script worked.

Error:
```  File "<string>", line 855
    <
SyntaxError: invalid syntax
```

The first php file: https://github.com/typecho/typecho/blob/master/var/Typecho/Request.php
The second php file: Any code starts with `<?php`

```python
import os
from phply.phplex import lexer
from phply.phpparse import make_parser


def export(items):
    result = []
    if items:
        for item in items:
            if hasattr(item, 'generic'):
                item = item.generic(with_lineno=True)
            result.append(item)

    return result


def main():
    files = ['Request.php', 'test1.php', 'test2.php']
    for i in files:
        filename = os.path.join(os.path.dirname(__file__), i)
        if not os.path.exists(filename):
            return {}

        with open(filename) as f:
            code = f.read()

        export(make_parser().parse(code, lexer=lexer, tracking=True))


main()
```

**Comment by soulseekah** [comment]
Show the test1 and test2 files, please.

**Comment by RicterZ** [comment]
```php
<?php
echo 123
```

**Comment by RicterZ** [comment]
I found a way yo fix it, but I have to reload phply module.
```python
def parser(filename):
    if not os.path.exists(filename):
        return {}

    with open(filename) as f:
        code = f.read()

    reload(phply.phplex)
    logger.debug('Parse file: %s' % filename)
    return export(make_parser().parse(code, lexer=phply.phplex.lexer, tracking=True))
```

**Comment by soulseekah** [comment]
Well yes, you can't parse unclosed files like that, you have to reset the lexer. This is defined behavior.
You don't need to reload it though, just do `lexer=phplex.lexer.clone()` to your parse call.

For example: `phpparse.parser.parse(data, lexer=phplex.lexer.clone())`
