### ISSUE TITLE
The 1.2.3 release missing on PyPI

### ISSUE THREAD

**Issue by nijel** [viraptor/phply#46]
Thanks for releasing 1.2.3 (https://github.com/viraptor/phply/commit/a0a8f680239d60f9dc09d7a079ca4cc5fe8c3271), however it seems to be only tagged in Git, but was not pushed to PyPI, can you please upload it there as well?

Thanks!

**Comment by viraptor** [comment]
Thanks! 1.2.4 should be up now.

**Comment by Deathnerd** [comment]
>Thanks! **1.2.4** should be up now.

Erm... Don't you mean 1.2.3? @viraptor

**Comment by viraptor** [comment]
No. 1.2.4
