### ISSUE TITLE
Pls help to make TreeHelper for Cud

### ISSUE THREAD

**Issue by Alexey-T** [viraptor/phply#47]
Can you help to write function via PHPLY, to make CudaText plugin?
This function gets list of PHP file lines, and must give list of header lines - for classes/functions. (Items for class functions are sub-items for classes).

Func is described here in CudaTree documentation
```
 def get_headers(filename, lines)
  - param "lines" is editor contents in CudaText
  - param "filename" is to support included files or something

function must return list of tuples: 
  (line_index, header_level, header_text, icon_index)

- field "line_index": 0-based index of editor line, which has tree node
- field "header_level": 1-based level of node (node of level K+1 is included in node of level K)
- field "header_text": caption of tree node
```

Eg, if PHP file has class A with 2 functions F1, F2, I need to get

[
(index0, 1, 'class A', -1),
(index1, 2, 'function F1', -1),
(index2, 2, 'function F2', -1),
]

Thanks in advance.

**Comment by viraptor** [comment]
Sorry, I don't think phply is a good project to implement this. It doesn't recover from errors and doesn't have a good streaming API. It requires the whole file for parsing. In practice it means that any small issue in the file that's being continuously edited would break the output.

You could try implementing a very simplified state tracker need on phply's lexer (detect class, function with the name following them and braces) and it should work better for this situation. I'm happy to accept a PR which does this, (it could be a project on its own as well) but don't really have time to work on it.
