### ISSUE TITLE
Default parameter of class constant

### ISSUE THREAD

**Issue by polikeiji** [viraptor/phply#5]
I think class constant can be default parameters, but it's not supported in phply/phpparser.py.

So I think phpparser.py should be modified as below.

``` diff
601c601,605
<                  | class_name AND VARIABLE EQUALS static_scalar'''
---
>                  | class_name AND VARIABLE EQUALS static_scalar
>                  | VARIABLE EQUALS class_constant
>                  | class_name VARIABLE EQUALS class_constant
>                  | AND VARIABLE EQUALS class_constant
>                  | class_name AND VARIABLE EQUALS class_constant'''
```

Thanks.

**Comment by soulseekah** [comment]
https://github.com/ramen/phply/pull/16 addresses this issue by adding `class_constant` as a possible variant of a `static_scalar`.

**Comment by viraptor** [comment]
Fixed. The change has been merged. Thanks!
